git:
  paging:
    colorArg: always
    pager: delta --features=git --paging=never
os:
  editPreset: "nvim-remote"
  copyToClipboardCmd: echo -n {{text}} | $YANK_COMMAND
keybinding:
  files:
    commitChanges: c
    commitChangesWithEditor: C
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
