git:
  paging:
    colorArg: always
    pager: delta --features=git --paging=never
os:
  editPreset: "nvim"
keybinding:
  files:
    commitChanges: C
    commitChangesWithEditor: c
gui:
  nerdFontsVersion: "3"
