[Editor]
Borderless = false
# Transparent = 0.9
RestoreWindowGeometry = true
FontFamily = "PlemolJP Console NF"
FontSize = 11
CachedDrawing = true
CacheSize = 400
DisableLigatures = true
Clipboard = true
ModeEnablingIME = ["insert", "cmdline_normal"]
IndentGuide = true
Macmeta = true
DrawBorder = true

[Lint]
Visible = true

[Statusline]
Visible = true
ModeIndicatorType = "textLabel"

[Tabline]
Visible = true

[ScrollBar]
Visible = true

[SideBar]
Visible = false
Width = 200
DropShadow = false
AccentColor = "#5596ea"

[FileExplore]
MaxDisplayItems = 30
