name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl
      - name: Install dotfiles
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          XDG_DATA_HOME: "$HOME/.local/share"
          ASDF_DATA_DIR: "$XDG_DATA_HOME/asdf"
          ASDF_CONFIG_FILE: "$XDG_CONFIG_HOME/asdf/.asdfrc"
          GOPATH: "$HOME/go"
          GOBIN: "$GOPATH/bin"
          DENO_INSTALL: "$HOME/.deno"
          PATH: "$ASDF_DATA_DIR/shims:$GOBIN:$DENO_INSTALL/bin:$PATH"
        run: |
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply r-okm --branch $BRANCH
      - name: Source .zshrc
        shell: zsh -el --pipefail {0}
        run: |
          source ${ZDOTDIR}/.zshrc
