name: CI

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"
      - "install.sh"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "install.sh"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
          key: ${{ matrix.os }}-cargo-${{ hashFiles('src/.chezmoiscripts/run_once_after_201-install-cargo-packages.sh') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-
      - run: |
          ./install.sh
      - run: |
          source ${ZDOTDIR}/.zshrc
        shell: zsh -el --pipefail {0}
