name: CI

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"
      - "install.sh"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "install.sh"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./install.sh
      - run: |
          source ${ZDOTDIR}/.zshrc
        shell: zsh -el --pipefail {0}
