name: Installation on Ubuntu x86_64

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends curl
      - name: Install dotfiles
        run: |
          branch=${{ github.head_ref }} || ${{ github.ref_name }}
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply r-okm --branch $branch
      - name: Exec zsh
        run: |
          exec zsh -l
      - name: Source zshrc
        shell: zsh {0}
        run: |
          source ${ZDOTDIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/zsh}/.zshrc
